config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :memberships
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_freeze', on: :member
  end

  root 'breweries#index'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { less_than_or_equal_to: ->(_) { Time.now.year} }

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  has_many :beers, :dependent => :destroy
  has_many :ratings, :through => :beers

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :require_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end

  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    order = params[:order] || 'name'

    @name_direction = 'asc'
    if session[:last_name_direction] == 'asc'
      @name_direction = 'desc'
    end
    session[:last_name_direction] = @name_direction

    @year_direction = 'asc'
    if session[:last_year_direction] == 'asc'
      @year_direction = 'desc'
    end
    session[:last_year_direction] = @year_direction

    if session[:last_order] == 'name'
      @active_breweries = case order
      when 'name' then (@name_direction == 'asc') ? @active_breweries.sort_by{ |b| b.name } : @active_breweries.sort_by{ |b| b.name }.reverse
        when 'year' then @active_breweries.sort_by{ |b| b.year }
      end

      @retired_breweries = case order
      when 'name' then (@name_direction == 'asc') ? @retired_breweries.sort_by{ |b| b.name } : @retired_breweries.sort_by{ |b| b.name }.reverse
        when 'year' then @retired_breweries.sort_by{ |b| b.year }
      end
    elsif session[:last_order] == 'year'
      @active_breweries = case order
        when 'name' then @active_breweries.sort_by{ |b| b.name }
        when 'year' then (@year_direction == 'asc') ? @active_breweries.sort_by{ |b| b.year } : @active_breweries.sort_by{ |b| b.year }.reverse
      end

      @retired_breweries = case order
        when 'name' then @retired_breweries.sort_by{ |b| b.name }
        when 'year' then (@year_direction == 'asc') ? @retired_breweries.sort_by{ |b| b.year } : @retired_breweries.sort_by{ |b| b.year }.reverse
      end
    else
      @active_breweries = case order
        when 'name' then @active_breweries.sort_by{ |b| b.name }
        when 'year' then @active_breweries.sort_by{ |b| b.year }
      end

      @retired_breweries = case order
        when 'name' then @retired_breweries.sort_by{ |b| b.name }
        when 'year' then @retired_breweries.sort_by{ |b| b.year }
      end
    end

    session[:last_order] = order
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  def list
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }

    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }

    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    def require_admin
      unless current_user.admin
        flash[:error] = "You must be an admin to delete this!"
        redirect_to @brewery
      end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th> <%= link_to 'Name', breweries_path(order:"name") %> </th>
    <th> <%= link_to 'Year', breweries_path(order:"year") %> </th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache "brewerylist-#{@order}", skip_digest: true do %>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<% end %>

<br>

<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-default"  %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="brname">Name</a> </th>
    <th> <a href="#" id="bryear">Year</a> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

  <h2><%= @brewery.name %>
    <% if not @brewery.active  %>
        <span class="label label-info">retired</span>
    <% end %>
  </h2>

  <p>
    <em>Established year:</em>
    <%= @brewery.year %>
  </p>

  <p>Number of beers <%= @brewery.beers.count%> </p>

  <ul>
    <% @brewery.beers.each do |beer| %>
      <li><%= link_to beer.name, beer %></li>
    <% end %>
  </ul>

  <% if @brewery.ratings.empty? %>
    <p>beers of the brewery have not yet been rated! </p>
  <% else %>
    <p>Has <%= pluralize(@brewery.ratings.count,'rating') %>, average <%= round(@brewery.average_rating) %> </p>
  <% end %>

<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>

<%= edit_and_destroy_buttons(@brewery) %>